export const VIDEO_STYLES = [
  { key: 'auto', en: 'Auto Style', vi: 'Phong cách tự động' },
  { key: 'anime_90s', en: '1990s Japanese Anime', vi: 'Hoạt hình Nhật Bản thập niên 1990' },
  { key: 'early_anime', en: 'Early Japanese Anime', vi: 'Hoạt hình Nhật Bản giai đoạn đầu' },
  { key: 'high_contrast_portrait', en: 'High-Contrast Portrait', vi: 'Chân dung tương phản cao' },
  { key: 'showa_retro', en: 'Classic Showa Style (70s-80s Japan)', vi: 'Phong cách Showa cổ điển (Nhật Bản thập niên 70–80)' },
  { key: 'vitality', en: 'Vitality', vi: 'Sức sống (Vitality)' },
  { key: 'instagram', en: 'Instagram Style', vi: 'Phong cách Instagram' },
  { key: 'film_aesthetic', en: 'Film Aesthetic', vi: 'Thẩm mỹ điện ảnh' },
  { key: 'retro_snapshot', en: 'Retro Snapshot', vi: 'Ảnh chụp hoài cổ' },
  { key: 'american_retro', en: 'American Retro Style', vi: 'Phong cách Mỹ cổ điển' },
  { key: 'american_vintage_poster', en: 'American Vintage Poster', vi: 'Áp phích cổ điển kiểu Mỹ' },
  { key: 'cute_cartoon', en: 'Cute Cartoon Style', vi: 'Hoạt hình dễ thương' },
  { key: 'shoujo_manga', en: 'Shoujo Manga Style', vi: 'Truyện tranh Shoujo' },
  { key: 'western_picture_book', en: 'Western Picture Book', vi: 'Sách tranh phương Tây' },
  { key: 'kawaii', en: 'Kawaii', vi: 'Dễ thương kiểu Nhật (Kawaii)' },
  { key: 'flat_illustration', en: 'Flat Illustration', vi: 'Minh họa phẳng' },
  { key: 'internet_nostalgia', en: 'Internet Nostalgia', vi: 'Hoài niệm Internet' },
  { key: 'picture_book_illustration', en: 'Picture Book Illustration', vi: 'Minh họa sách tranh' },
  { key: 'childrens_picture_book', en: 'Children’s Picture Book', vi: 'Sách tranh thiếu nhi' },
  { key: 'traditional_chinese_painting', en: 'Traditional Chinese Painting', vi: 'Tranh thủy mặc Trung Hoa cổ điển' },
  { key: 'lofi_illustration', en: 'Lo-fi Illustration', vi: 'Minh họa Lo-fi' },
  { key: 'japanese_anime', en: 'Japanese Anime Style', vi: 'Hoạt hình Nhật Bản' },
  { key: '2d_cartoon', en: '2D Cartoon', vi: 'Hoạt hình 2D' },
  { key: 'riso_print', en: 'Riso Print Style', vi: 'In Riso' },
  { key: 'pixel_art', en: 'Pixel Art', vi: 'Nghệ thuật Pixel' },
  { key: 'chinese_style_portrait', en: 'Chinese Style Portrait', vi: 'Chân dung phong cách Trung Hoa' },
  { key: '3d_cartoon', en: '3D Cartoon', vi: 'Hoạt hình 3D' },
  { key: 'stop_motion', en: 'Stop-Motion Animation Style', vi: 'Hoạt hình stop-motion' },
  { key: 'game_90s', en: '1990s Video Game Style', vi: 'Trò chơi điện tử thập niên 1990' },
  { key: 'voxel_art', en: 'Voxel Art Style', vi: 'Nghệ thuật Voxel' },
  { key: 'low_poly', en: 'Low Poly Style', vi: 'Phong cách Low Poly' },
  { key: 'american_comic', en: 'American Comic Style', vi: 'Truyện tranh Mỹ' },
  { key: 'heavy_brushstroke_painting', en: 'Heavy Brushstroke Painting', vi: 'Tranh sơn dầu nét cọ dày' },
  { key: 'semi_painted_illustration', en: 'Semi-Painted Illustration', vi: 'Minh họa bán sơn dầu' },
  { key: 'fantasy', en: 'Fantasy Style', vi: 'Phong cách giả tưởng' },
  { key: 'romance_novel_cover', en: 'Romance Novel Cover', vi: 'Bìa tiểu thuyết lãng mạn' },
  { key: 'concept_art', en: 'Concept Art', vi: 'Nghệ thuật ý tưởng' },
  { key: 'hong_kong_film', en: 'Hong Kong Film Style', vi: 'Phong cách phim Hồng Kông' },
  { key: 'cinematic', en: 'Cinematic Style', vi: 'Phong cách điện ảnh' },
  { key: 'documentary', en: 'Documentary Film Style', vi: 'Phim tài liệu' },
  { key: 'light_film_texture', en: 'Light Film Texture', vi: 'Phim ánh sáng mềm' },
  { key: 'ricoh_photography', en: 'Ricoh Photography Style', vi: 'Nhiếp ảnh Ricoh' },
  { key: 'romance_film', en: 'Romance Film Style', vi: 'Phim lãng mạn' },
  { key: 'sitcom', en: 'Sitcom Style', vi: 'Phim sitcom' },
  { key: 'road_movie', en: 'Road Movie', vi: 'Phim hành trình trên đường' },
  { key: 'western_film', en: 'Western Film', vi: 'Phim miền Tây' },
  { key: 'wuxia_film', en: 'Wuxia Film', vi: 'Phim võ hiệp' },
  { key: 'hong_kong_noir', en: 'Hong Kong Noir', vi: 'Phim noir Hồng Kông' },
  { key: 'mystery_film', en: 'Mystery Film', vi: 'Phim bí ẩn' },
  { key: 'horror_film', en: 'Horror Film', vi: 'Phim kinh dị' },
  { key: 'dc_cinematic', en: 'DC Cinematic Style', vi: 'Phong cách điện ảnh DC' },
  { key: 'war_film', en: 'War Film', vi: 'Phim chiến tranh' },
  { key: 'vintage_photography', en: 'Vintage Photography', vi: 'Nhiếp ảnh cổ điển' },
  { key: 'fashion_photography', en: 'Fashion Photography', vi: 'Nhiếp ảnh thời trang' },
  { key: 'wasteland', en: 'Wasteland Style', vi: 'Phong cách hoang mạc' },
  { key: 'retro', en: 'Retro Style', vi: 'Phong cách retro' },
  { key: 'pastoral', en: 'Pastoral Style', vi: 'Phong cách đồng quê' },
  { key: 'urban_photography', en: 'Urban Photography', vi: 'Nhiếp ảnh đô thị' },
  { key: 'car_photography', en: 'Car Photography', vi: 'Nhiếp ảnh xe hơi' },
  { key: 'pet_photography', en: 'Pet Photography', vi: 'Nhiếp ảnh thú cưng' },
  { key: 'product_photography', en: 'Product Photography', vi: 'Nhiếp ảnh sản phẩm' },
  { key: 'landscape_photography', en: 'Landscape Photography', vi: 'Nhiếp ảnh phong cảnh' },
  { key: 'ecological_photography', en: 'Ecological Photography', vi: 'Nhiếp ảnh sinh thái' },
  { key: 'street_photography', en: 'Street Photography', vi: 'Nhiếp ảnh đường phố' },
  { key: 'still_life_photography', en: 'Still Life Photography', vi: 'Nhiếp ảnh tĩnh vật' },
  { key: 'lego_animation', en: 'Lego Animation', vi: 'Hoạt Hình lắp ghép (Lego)' },
];

export const DIALOGUE_LANGUAGES = [
  { key: 'vi', label: 'Tiếng Việt' },
  { key: 'en', label: 'English' },
  { key: 'ko', label: '한국어 (Korean)' },
  { key: 'ja', label: '日本語 (Japanese)' },
  { key: 'zh', label: '中文 (Chinese)' },
];